import { processDocument } from "../services/fileProcessor";
import { extractStructuredData } from "../services/aiExtractor";
import { insertCaseEvents, insertCaseParties, insertCasePayments, insertMissingDocuments } from "../lib/db";
import { ensureSupabase } from "../lib/supabase";
import { log } from "../utils/logger";
import { ensureBucket } from "../lib/storage";
import { nanoid } from "nanoid";

// Minimal Express-style route handler
export async function uploadDocumentRoute(req: any, res: any) {
  try {
    const supabase = ensureSupabase();
    if (!supabase) {
      return res.status(500).json({ error: "Supabase not configured" });
    }
    const file = req.file;
    if (!file?.buffer) {
      return res.status(400).json({ error: "Missing file buffer" });
    }

    const fileBuffer: Buffer = file.buffer;
    const fileName = `${nanoid()}-${file.originalname}`;

    // ensure storage bucket exists (best-effort)
    const bucketEnsured = await ensureBucket(supabase, "documents", false);
    if (!(bucketEnsured as any).ok) {
      return res.status(500).json({ error: "Storage bucket 'documents' missing and could not be created" });
    }

    // 1. Upload to Supabase storage
    // Convert Buffer to ArrayBuffer to satisfy storage SDK in all runtimes
    const ab = fileBuffer.buffer.slice(fileBuffer.byteOffset, fileBuffer.byteOffset + fileBuffer.byteLength);
    const { data: uploadData, error: uploadErr } = await (supabase as any).storage
      .from("documents")
      .upload(fileName, ab as ArrayBuffer, { contentType: file.mimetype || "application/octet-stream", upsert: false });

    if (uploadErr) {
      log("Supabase storage upload error", uploadErr);
      return res.status(500).json({ error: "Failed to upload file", details: uploadErr?.message || uploadErr });
    }

    // 2. Insert metadata into new schema documents table
    const publicUrl = (supabase as any).storage.from("documents").getPublicUrl(uploadData.path).data?.publicUrl || null;
    let documentId: string | null = null;
    let storedDoc: any = null;
    // Try new schema first
    {
      const { data: insertData, error: insertErr } = await (supabase as any)
        .from("documents")
        .insert({
          // id will be generated by DB (uuid)
          filename: file.originalname,
          file_url: publicUrl || uploadData.path,
          status: "pending",
        })
        .select();
      if (!insertErr && insertData?.[0]) {
        storedDoc = insertData[0];
        documentId = storedDoc?.id || null;
      } else if (insertErr) {
        // Fallback to legacy schema if new columns do not exist
        const legacyId = nanoid();
        const { data: legacyIns, error: legacyErr } = await (supabase as any)
          .from("documents")
          .insert({
            document_id: legacyId,
            file_name: file.originalname,
            file_path: uploadData.path,
            created_at: new Date().toISOString(),
          })
          .select();
        if (legacyErr) {
          return res.status(500).json({ error: "DB Insert Failed", details: insertErr?.message || legacyErr?.message || insertErr || legacyErr });
        }
        storedDoc = legacyIns?.[0] || null;
        documentId = storedDoc?.document_id || legacyId;
      }
    }

    if (!documentId) {
      return res.status(500).json({ error: "DB Insert Failed", details: "No document id returned" });
    }

    // 3. OCR + preprocess
    let processed: any = null;
    try {
      processed = await processDocument(fileBuffer, file.originalname);
    } catch (ocrErr) {
      log("OCR/processing failed (non-blocking)", ocrErr);
      processed = { cleanedText: "", engine: "none", pages: [], rawText: "" };
    }
    try {
      const { logExtraction } = await import("../utils/extractionLogger");
      logExtraction({
        timestamp: new Date().toISOString(),
        status: "success",
        model: "ocr",
        documentId,
        // Include a small preview of extracted text only (first 500 chars)
        error: undefined,
        validationErrors: undefined,
      } as any);
      // Write raw OCR text to a sidecar file for debugging (first 2000 chars)
      const fs = await import("fs");
      const path = await import("path");
      const dir = path.join(process.cwd(), "logs");
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
      const ocrPreview = String(processed?.rawText || "").slice(0, 2000);
      fs.writeFileSync(path.join(dir, `ocr-${documentId || "pending"}.txt`), ocrPreview, { encoding: "utf8" });
    } catch (_) {
      // best effort
    }

    // 4. OPTIONAL: trigger extraction pipeline and persist results
    try {
      const extraction = await extractStructuredData(processed.cleanedText || "");
      if (documentId) {
        await insertCaseEvents(documentId, extraction.events || []);
        await insertCaseParties(documentId, extraction.parties || []);
        await insertCasePayments(documentId, extraction.payments || []);
        await insertMissingDocuments(documentId, extraction.missingDocuments || []);
      }
    } catch (ex) {
      log("upload: async extraction failed (non-blocking)", ex);
    }

    // 5. Mark document processed
    // Attempt to mark processed for new schema; ignore error for legacy
    await (supabase as any)
      .from("documents")
      .update({ status: "processed" })
      .eq("id", documentId);

    return res.json({ success: true, document: { id: documentId, ...storedDoc } });
  } catch (e) {
    log("Unexpected upload error", e);
    return res.status(500).json({ error: "Unexpected error" });
  }
}
